version: '3.8'
services: 

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Compaq*87
    ports:
      - "8082:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    #  - ./mlflow/init.sql:/docker-entrypoint-initdb.d/init.sql
    #healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 10
    networks:
      - networkp3-2025
    #restart: always

networks:
  networkp3-2025:
    external: true
    name: networkp3-2025