# Usa la imagen oficial de Python 3.9 como base

FROM python:3.9

WORKDIR /app

COPY app_back/requirements_api.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY app_back/main.py /app/main.py
COPY models /app/models
COPY connections /app/connections

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]